### ISSUE TITLE
Alphabetize the functions?

### ISSUE THREAD

**Issue by rileypaulsen** [Ayush6968/Javascript-Array-cheatsheet#5]
For easier finding.

**Comment by ayushgptaa** [comment]
Wow this a very good suggestion. I'll try to implement this as soon as possible. Thank you 😊.

**Comment by wiktoriavh** [comment]
I can understand why that could be a nice idea, but I honestly would not do that, because some methods are very similar but have distinctions, like `forEach` and `map`. I would keep it in the same groups they are in. This is more helpful for beginners.
